travis:
  secure:
    BINSTAR_TOKEN: gg0SM6bWuAFoRYwd1wiUCPY23opeDx/lLc5g3kjaRy4KH3wiDH8Zo9Q1OwDp6Juq9TM9ZeiD8berpHDtg6QXIPC2rcu9btsOFlFFgiZF7g6nQSEDGQrv7a0NGir6ZKcYOs2gugYEQZ2ijM/huuJcngDc+tGCuABsJkQwdsrgHuvJl/1fBfcz60F4idu3mibAJ9sEwImh5leVeMKbY2n8w6OWX8pA/3sFtjB6QDkcdzJXOuJgHDwOHTloU7/DUWmMWBKRQH0anuNULRAY94yoFLSQ7kxbo5YSPNvFGKOSeJkdvEfBo+I3eflii9fbl0v8zJjnth2nIM4te3obKZ8deKyhY+Ty0OcJOZTRgNsMkxbQJoXvXDHr5CEYHpTxcJAg3Fdqc8PNcZ5eJSzHvSES8z1aJFw9AqwCGbBS/ElHt/SA0duIU6C5cVaralhHvRmlOUhGgN56cMa/ALDq3hEqzeUgWbUYM0WzVbHtuuCbqR06V1UwDI7grdd17sHqpZF9rbzqOnjPRt01cdQzBfHvPS2z5o/za0X9QRQOrfFWNKuRQgMYC0oC8+aqiT+4tevbDqRXug1Eixh0Vmp1LvrjzyJQEDwBVN/Hn/XUQQ7ciTjyc2BB9wRxbhOG8POac9XvAoyWnN2pB11xtxAz/ZHsvYbdjXKn3eORahBGHHIzBfA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
