travis:
  secure:
    BINSTAR_TOKEN: 2EqQmJzTl7S7Wad5HU21pMWbYhyjhbQrsiGEimQoUyIqAeXjrKbUcesUwTkroCrx/RpLeJL7EWNv3WNT1JwJX07jDBWoNt72GV4DXUtPHXlzA4eBYtfrFjoqqEGNz8XIxdmxAinJcIPChp26OIQQOSs6aGkP99sj3z6RaCjjkg9iy8VNefTUe0ulhgEbMR3kB/ctL6iM+kO3+SjLlu1InzOdJAlGxZkbxU4q1HavcNx6DF+9/Z+YULvUsuv36PF41Ms8+QqxYS6pJ066hKrCHHLLsmuwW2+84+tCxobK0KD/DAX/6/F13Ver5LblVw3j+PkG4J2gPs9OzNE5TEsY9uDwFLiE6Uw1loSHxkYss0jr41yc4AMZy0tWTSnN+mO6J5yFGP7wNR+IviMhNCAhZsXT6ZW1aWp7KoCG04gfsyKm6V5qZT7+JdoLb9QBTz83HCwBMEL81N2wQkSPUtFetHcriUrC6ljEdsgALgED7yC37RUplwaHv9moAHxBSrjuvSCNJ7+SmN7dthVYELSb5IUCeSRN8h1LwGNtwFXVRMblGqNKjoQA3mkH2fyOcT8WMLmtCTXhorX6PK1VtPRjaoF8lEvL9ESJEdGiDrejLcxkGH/ljGAZv2Fjh4UAqGc/5X6nS+2plq+6kuIhusDxQz8pGN/d7q7phxWOLQz1Wqo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
